server:
  port: 20000

spring:
  application:
    name: user-service

  datasource:
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.69:30306/msa?serverTimezone=Asia/Seoul
  output:
    ansi:
      enabled: always

  # zipkin:
  #   base-url: http://localhost:9411
  #   enabled: true

  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: none
    properties:
      hibernate.format_sql: false
    show-sql: true
    open-in-view: false

# sql:
#   init:
#     platform: mysql

mh:
  value: "abcdefg"

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  #      defaultZone: http://localhost:8762/eureka, http://kubernetes.docker.internal:8763/eureka
#
#  instance:
#    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}
#    prefer-ip-address: true

#logging:
#  level:
#    com.green.userservice.feignclient: DEBUG
#  pattern:
#    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

# management:
#   tracing:
#     sampling:
#       probability: 1.0
#     propagation:
#       consume: B3
#       produce: B3
#   zipkin:
#     tracing:
#       endpoint: http://localhost:9411/api/v2/spans

# refresh 가 되는 설정
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
# jwt 비밀번호

logging:
  level:
    org.springframework.web: DEBUG    # HTTP 요청 관련 로그 (Actuator HTTP 엔드포인트) 이거 해야 다 나옴...
  pattern:
    correlation: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
#  pattern:
#    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  # 파일 로그 패턴

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0 # 모든 요청을 추적 (0.1로 설정하면 10%만 추적)
    zipkin:
      enabled: true
      endpoint: http://192.168.0.69:9411/api/v2/spans

token:
  access_token_expiration_time: 86400 # 하루
  refresh_token_expiration_time: 2592000 # 한달
  secret: abcdefghijklmnopqrstuvwxyz01234567890

gateway:
  ip: 127.0.0.1

first-service-url: http://localhost:40001
order-service-url: http://localhost:20001