
spring:
  application:
    name: ex10

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.40:3306/pmh
#    url: jdbc:mariadb://192.168.0.49:3307/mymariadb
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    show-sql: true
    open-in-view: false

my:
  value: "welcome to my value"