server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/leetorrl/spring-cloud-config
          default-label: main

#환경설정 변경되면 refresh post 요청
management:
  endpoints:
    web:
      exposure:
        include: "*"