#server:
#  port: 10000

spring:
  application:
    name: ex11
#    spl문 실행하여라
  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://maria-container:3307/db

    url: jdbc:mariadb://192.168.0.69:3307/db

#    url: jdbc:mariadb://121.181.223.164:3307/db

#    url: jdbc:mariadb://192.168.0.35:3307/db
    #    url: jdbc:mariadb://192.168.0.40:3306/pmh
#    url: jdbc:mariadb://192.168.0.40:3306/mypmhdb
#    url: jdbc:mariadb://192.168.0.65:3306/cew


    username: root
    password: 1234


  jpa:
    hibernate:

      ddl-auto: create
#      ddl-auto: none
#      ddl-auto: update

    properties:
      hibernate.format_sql: true
    show-sql: true
    open-in-view: false

    defer-datasource-initialization: true

  servlet:           #파일 업로드 자동완성 안됨....
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB  #파일 용량 사이즈
      file-size-threshold: 0  #파일 등록갯수 0일시 에러
      enabled: true

my:
  value: "welcome to my value"

